# 2023-04-17

## asyncio 공부

장기적으로, 데이터 수집할 때 사이트 크롤링이 중요할 것 같고  
당연히 비동기 http 요청 능력 역시 필수적일 것 같아 python asyncio 기본 문법을 조금 공부했다.

(httpx 라이브러리만 잘 써도 될 것 같긴 한데, 최소한 기본적인 asyncio 정도는 알아야 할 것 같아서..)

### async def

async def를 먼저 봤다.

```python
import asyncio
from random import random

async def square(x):
    await asyncio.sleep(random())
    return x**2

print(type(square))  # <class 'function'>
print(type(square(2)))  # <class 'coroutine'> (with RuntimeWarning)
print(type(await square(2)))  # <class 'int'>
```

보다시피 `square`는 type이 `function`이지만, `square(2)`는 type이 `int`가 아니다. 함수를 실행하면 바로 결과값이 나오는 익숙한 방식이 아니라, `async def`로 선언된 함수는 실행하면 `coroutine`(이하 코루틴) 객체를 반환한다. 이 코루틴 객체는 `await` 구문을 통해 실행되며, `await square(2)` 구문에서야 `4`라는 `int`형 객체를 반환한다.

### 첫 시도

`async def`와 `await`를 봤으니 아래 코드를 가장 먼저 실험해봤다. 
`[1, 2, 3]`을 입력받으면 `[1, 4, 9]`를 출력하되, random하게 `sleep`을 집어넣어 비동기로 연산하는 것을 의도했다.

```python
import asyncio
from random import random

async def square(x):
    # print(x)
    await asyncio.sleep(random())
    return x**2

async def wait_list(arr):
    result = [await square(x) for x in arr]
    
    return result

await wait_list(range(10))
```

하지만 실행해보면, 주석처리된 `print(x)`에 의한 출력이 선형적으로 나왔다. 생각해보니 `wait_list`의 `await square(x)`를 선형적으로 실행하니 당연한 결과였다.


### 두 번째 시도

의도한 결과를 찾아내기 위해 구글링을 하다가 `gather`라는 기능을 알았다.

```python
async def wait_list(arr):
    tasks = [square(x) for x in arr]
    results = await asyncio.gather(*tasks)

    for result in results:
        print(result)
```

`wait_list` 함수의 구현만 위와 같이 바꿨다.

`gather`는 코루틴 객체들의 리스트를 인자로 받아 전부 실행시킨다. 그리고 모든 객체들이 실행 완료되면 합쳐진 실행결과의 리스트를 반환한다.

이 정도 설명만 알고 코드를 돌려서 '뒤죽박죽'이 되기를 원했지만,,, 그렇지 않았다. 공식 문서를 읽어보면 `gather`는 입력된 순서를 보존하여 출력한다.

### 세 번째 시도

결국 참지 못하고 다시 chatGPT에게 도움을....  
chatGPT는 신이다. `as_completed`라는 구문을 알려줬다.

`wait_list` 구문을 아래와 같이 고친다.
```python
async def wait_list(arr):
    tasks = [square(x) for x in arr]

    for future in asyncio.as_completed(tasks):
        result = await future
        print(result)
```

처음 이 코드를 보고, 이미 `for` 구문에 들어가버린 코드를 어떻게 순서를 뒤집지?라는 생각을 했다. 다행히 chatGPT의 아래와 같은 설명을 보고 이해되었다.

"`as_completed`는 각 `task`가 완료되는 순서대로 반환하는 반복자를 생성합니다."

`as_completed`가 반복자를 반환하므로, 결국 위의 `for`구문은 각 future가 완료되는 순서대로 실행되는 것이다. 

하지만 여전히 헷갈리는 점이 있다. `as_completed`가 실행이 완료되는 순서대로 반복자를 반환한다는 것은, 이미 내부적으로는 모든 코루틴들이 실행에 들어갔다는 것 아닌가? 그러면 `await future`이라는 구문이 왜 필요한 지 이해가 되지 않았다. 내가 이해한 바로는 `await`는 뒤에 오는 코루틴 객체를 실행하는 구문인데... 이미 실행된 코루틴 객체들을 왜 또 실행시킨다는 말인가?

### `as_completed` 내부 코드 확인

다행히 F12 누르니 구현이 떴다. 아래와 같다.

```python
def as_completed(fs, *, timeout=None):
    """Return an iterator whose values are coroutines.

    When waiting for the yielded coroutines you'll get the results (or
    exceptions!) of the original Futures (or coroutines), in the order
    in which and as soon as they complete.

    This differs from PEP 3148; the proper way to use this is:

        for f in as_completed(fs):
            result = await f  # The 'await' may raise.
            # Use result.

    If a timeout is specified, the 'await' will raise
    TimeoutError when the timeout occurs before all Futures are done.

    Note: The futures 'f' are not necessarily members of fs.
    """
    if futures.isfuture(fs) or coroutines.iscoroutine(fs):
        raise TypeError(f"expect an iterable of futures, not {type(fs).__name__}")

    from .queues import Queue  # Import here to avoid circular import problem.
    done = Queue()

    loop = events._get_event_loop()
    todo = {ensure_future(f, loop=loop) for f in set(fs)}
    timeout_handle = None

    def _on_timeout():
        for f in todo:
            f.remove_done_callback(_on_completion)
            done.put_nowait(None)  # Queue a dummy value for _wait_for_one().
        todo.clear()  # Can't do todo.remove(f) in the loop.

    def _on_completion(f):
        if not todo:
            return  # _on_timeout() was here first.
        todo.remove(f)
        done.put_nowait(f)
        if not todo and timeout_handle is not None:
            timeout_handle.cancel()

    async def _wait_for_one():
        f = await done.get()
        if f is None:
            # Dummy value from _on_timeout().
            raise exceptions.TimeoutError
        return f.result()  # May raise f.exception().

    for f in todo:
        f.add_done_callback(_on_completion)
    if todo and timeout is not None:
        timeout_handle = loop.call_later(timeout, _on_timeout)
    for _ in range(len(todo)):
        yield _wait_for_one()
```

각 task에 완료시 callback을 걸어놓고, 반복 `_wait_for_one`구문으로 전체를 실행하는 건 알겠는데, 여기에 `f = await done.get()` 구문이 있다...? `done`이 내부적으로 정의된 `Queue` type이고, `get`함수의 구현을 보니 또 안에 `await getter`라는 구문이 있다. 

`Queue` 내부 구현까지는 다 읽어볼 시간도 부족하고 이해도도 부족하다는 게 느껴졌다. 특히 `Queue`의 주석에 "producer and consumer coroutines"라는 표현이 있는데, 이 부분은 더 공부가 필요하다고 느꼈다.

일단은 파이썬 공식 문서에서 제공하는 `as_completed` 구문을 관례처럼 외워야겠다.

### 이벤트 루프

[NHN Cloud 블로그](https://meetup.nhncloud.com/posts/89)에 아주 잘 설명이 되어 있다.

`main()`의 실행이 종료되어도 이벤트 루프는 남아있어 여전이 `task queue`에 작업을 전달할 수 있다는 것이 좀 충격적이었다. main 함수가 끝나도 다 끝난 게 아닐 수가...?

